import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Peking Roasted Duck',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Chinese'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['Zhejiang Cuisine', 'Fujian Cuisine', 'Anhui Cuisine'],
  },
  {
    id:'2',
    name: 'Kung Pao Chicken',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['Chinese'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Anhui Cuisine'],
  },
  {
    id:'3',
    name: 'Sweet and Sour Pork',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['Chinese'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['Zhejiang Cuisine', 'Sweet and Sour Pork'],
  },
  {
    id:'4',
    name: 'Hot Pot',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['Chinese'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['Zhejiang Cuisine', 'Fry'],
  },
  {
    id:'5',
    name: 'Dim Sum',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['Chinese'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Dumplings',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['Zhejiang Cuisine', 'Fujian Cuisine', 'Anhui Cuisine'],
  },
  {
    id:'7',
    name: 'Ma Po Tofu',
    price: 12,
    cookTime: '20-30',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'assets/food-7.jpg',
    tags: ['Zhejiang Cuisine', 'Burger', 'Anhui Cuisine'],
  },
  {
    id:'8',
    name: 'Char Siu',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'assets/food-8.jpg',
    tags: ['Zhejiang Cuisine', 'Fujian Cuisine', 'Anhui Cuisine'],
  },
  {
    id:'9',
    name: 'Chow Mein',
    price: 15,
    cookTime: '45-50',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'assets/food-9.jpg',
    tags: ['Zhejiang Cuisine', 'Fujian Cuisine', 'Anhui Cuisine'],
  },
  {
    id:'10',
    name: 'Fried Rice',
    price: 14,
    cookTime: '45-50',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'assets/food-10.jpg',
    tags: ['Zhejiang Cuisine', 'Fujian Cuisine', 'Anhui Cuisine'],
  },
  {
    id:'11',
    name: 'Sichuan Pork',
    price: 10,
    cookTime: '45-50',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'assets/food-11.jpg',
    tags: ['Zhejiang Cuisine', 'Fujian Cuisine', 'Anhui Cuisine'],
  },
  {
    id:'12',
    name: 'Xiaolongbao',
    price: 11,
    cookTime: '45-50',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'assets/food-12.jpg',
    tags: ['Zhejiang Cuisine', 'Fujian Cuisine', 'Anhui Cuisine'],
  },
  {
    id:'13',
    name: 'Zhajiangmian',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'assets/food-13.jpg',
    tags: ['Zhejiang Cuisine', 'Fujian Cuisine', 'Anhui Cuisine'],
  },
  {
    id:'14',
    name: 'Wonton Soup',
    price: 10,
    cookTime: '45-50',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'assets/food-14.jpg',
    tags: ['Zhejiang Cuisine', 'Fujian Cuisine', 'Anhui Cuisine'],
  },
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 14 },
  { name: 'Zhejiang Cuisine', count: 4 },
  { name: 'Fujian Cuisine', count: 3 },
  { name: 'Anhui Cuisine', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Sweet and Sour Pork', count: 2 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]
